### PR TITLE
Fix padding off by one

### LINKED ISSUE #14: Padding is off by one
Passing a padding argument (`-p, --padding`) results in one more padding line than specified, as `writeln` already includes one newline.

### PR DESCRIPTION
**Pull request by simonwiles**
Fixes #14

### CODE REVIEW

**Comment by samwho** [comment]
Hey @simonwiles! Thanks for pointing this out and producing a PR. Would you be able to add some tests for this? 🙏

**Comment by simonwiles** [comment]
Sure thing.  I'm going to have to do some work to understand how the testing system works first, so it might take me a short while 🙂👍️

**Comment by simonwiles** [comment]
Will something like this be adequate?

**Comment by samwho** [comment]
This is perfect! 🙏

**Pull request merged**
